### ISSUE TITLE
Missing Mandarin Chinese

### ISSUE THREAD

**Issue by brauliobo** [rmm5t/iso639#3]
```
jruby-9.1.13.0 :002 > Iso639['cmn']
 => nil 
```
https://iso639-3.sil.org/code/cmn

**Comment by rmm5t** [comment]
Hi @brauliobo. Thanks for reporting this. Right now, all codes are sourced from 
http://www.loc.gov/standards/iso639-2/ascii_8bits.html

This list apparently doesn't include all the ISO 639-3 codes. I'm open to added more languages, but I'll need a new (easily digestible) source file for all ISO 639-2 and ISO 639-3 mappings.

**Comment by brauliobo** [comment]
Hey @rmm5t, I ended up mapping the missing languages of https://www.apache.org/dist/opennlp/models/langdetect/1.8.3/README.txt manually (`["cmn", "ekk", "lvs", "nan", "pes", "plt", "pnb"]`)
